name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
	  messages=""
	  commits=$${{ github.event.commits }}
	  length=${#commits[@]}
    	  for (( i = 0; i < length; i++ )); do
      	    messages+="${{ commits[i].message }}\n"
    	  done
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s '/Applications/Xcode_26.2.app/Contents/Developer'
      - run: fastlane beta --verbose
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MATCH_PERSONAL_ACCESS_TOKEN }}
          COMMIT_MESSAGES: ${{ messages }}
