name:compile-messages 

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  compile-messages:
    runs-on: macos-latest
    steps:
	- name: Create Changelog
  	id: changelog
  	uses: actions/github-script@v6.3.1
  	env:
    	  COMMITS: ${{ toJSON(github.event.commits) }}
  	with:
    	  result-encoding: string
    	  script: |
        	const commits = JSON.parse(process.env.COMMITS);
        	var lines = "## Whatâ€™s Changed\n\n";
        	for (const commit of commits) {
                  lines += "- " + commit.message + " (" + commit.id + ") @" + commit.author.username + "\n"
        	}
		echo lines
        	return lines
